### ISSUE TITLE
Write manuscript

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/apex#16]
I have started writing a paper to describe the package. Will send invites to the google doc soon. We need to fix a few things in the package before I think.

**Comment by thibautjombart** [comment]
I will send an email with a link to the google doc. Please contact me if you don't receive it.

**Comment by EricArcher** [comment]
Is the ms still v1.1 on google drive? It shows for me as being last accessed Sep 25, 2015...

**Comment by thibautjombart** [comment]
Not sure.. I'll PM you a link to the current one.

**Comment by thibautjombart** [comment]
Done
