### ISSUE TITLE
Add translator from multidna to genind

### ISSUE THREAD

**Issue by zkamvar** [thibautjombart/apex#2]
I am taking care of this.

**Comment by thibautjombart** [comment]
Sorry just saw this.. done! :-/

**Comment by zkamvar** [comment]
Working on adding an MLST argument to it. Probably want to have an argument to convert 100% gaps to missing.

**Comment by thibautjombart** [comment]
Awe-fck!g-some =D

**Comment by thibautjombart** [comment]
Can we close this one now?
