### ISSUE TITLE
export to seqinr format

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/apex#25]
for both multidna and multphyDat?

**Comment by KlausVigo** [comment]
@thibautjombart 
You mean the alignment class in seqinr? That's a good idea.
Just had a short look there exists (non-generic) functions (as.alignment) in both ape and seqinr, which could cause potentially problems if we decide to call ape:::as.alignment.
I will write a function in phangorn to do this for phyDat objects, has the advantage that it also should work for amino acids.

**Comment by thibautjombart** [comment]
Cool!

**Comment by thibautjombart** [comment]
BTW to stay coherent we probably want to call the functions `multidna2alignment` and `multiphyDat2alignment`

**Comment by KlausVigo** [comment]
Added the functions, at the moment just with concatenate. Requires newest phangorn from github.

**Comment by thibautjombart** [comment]
Awesome

**Comment by thibautjombart** [comment]
@KlausVigo I think this will break Travis as it installs CRAN version of the dependencies. Can we \ \dontrun the example?
