### ISSUE TITLE
Add type of data stored in multiphyDat

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/apex#26]
I would rename @dna to @seq and create a new @type to store the data type.

**Comment by KlausVigo** [comment]
@thibautjombart 
I will do this for multiphyDat and in phangorn parallel later today (at night in Europe). As I have the workshop with Emmanuel next week and try not break things or minimize the chances of doing so.

**Comment by thibautjombart** [comment]
;)

**Comment by KlausVigo** [comment]
@thibautjombart 
If I rename @dna to @seq than it seems I have to do this also for multidna objects, as setClass("multiphyDat", contains="multidna").

**Comment by thibautjombart** [comment]
Damn, I forgot that, you are right. The problem of doing so is loosing backward compatibility. We should have used accessors right away. I think the best course of action might be:
- cancel the inheritance on multidna
- replace by inheritance on a common, virtual class, which keeps the common bits of multidna and multiphyDat

I'll give it a shot this afternoon. Also adding issues for accessors.

**Comment by thibautjombart** [comment]
OK, should be working now. @KlausVigo maybe worth checking that the multiphyDat constructor is OK. Also, you will need to replace the @dna by @seq in pmlPart (currently crashes the vignette so I commented it out).
