### ISSUE TITLE
Create and use accessors

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/apex#31]
We need accessors for:
- [ ] the sequences
- [ ] the individual labels
- [ ] the total number of sequences
- [ ] the number of gap-only sequences
- [ ] the number of individuals

I would suggest `getThisStuff()` as a general form?

**Comment by EricArcher** [comment]
I've been making accessors for the `<multidna>` sequences slot in my new gtypes object in the new version of strataG (https://github.com/EricArcher/strataG.devel), so I'll tackle this today. Have patience with me, I'm still a GitHub newbie.

**Comment by thibautjombart** [comment]
Sounds great, thanks! =D

**Comment by EricArcher** [comment]
Do you mind if I change the names you have in the `<accessors.R>` file? For instance, it makes more sense to me to have `<getSequences>` return the actual sequences and something like `<getLoci>` return the locus names, and `<getIndNames>` to get the individual names for a locus.

**Comment by thibautjombart** [comment]
Not at all, it's actually best to change them. All the code is old stuff
from adegenet but I never used it in apex. Feel free to delete all the
commented code and start from a clean slate.

**Comment by EricArcher** [comment]
Roger that.

**Comment by EricArcher** [comment]
Is there always a sequence for every individual in each locus of the `@dna` slot (either filled with gaps or with actual sequence)? Or, are you planning on changing it so that each locus can have different individuals?
I'm trying to workout if the return value for `getSequenceNames` should be a list with a character vector for each locus, or just a single character vector.

**Comment by EricArcher** [comment]
I've pushed (I think) accessors for `multidna` in `accessors.R` and added some functions to `internal.R`. `getNumSequences` has a `gap.only` argument, which when set to `TRUE` should duplicate the functionality of the `nMissingSequences` internal function, so you may want to get rid of that one.
Let me know if I've borked anything.

**Comment by thibautjombart** [comment]
We've changed that bit in the devel. Used to be same individuals for every
gene, with gap only sequences where needed. This is now optional, so you
may have different numbers of sequences for each gene. I think a generic
way to name sequences would be [gene].[individual] or something along these
lines?

**Comment by thibautjombart** [comment]
Awesome! I will check it ASAP. Got a meeting tomorrow all day, but will try
to run a sneaky pull & check :)
Cheers

**Comment by thibautjombart** [comment]
Checked and it looks great, thanks!
