### ISSUE TITLE
Document accessors in vignette

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/apex#36]

**Comment by thibautjombart** [comment]
Hi @EricArcher! I'm just catching up with apex as I am wrapping up the MS. Where are we at with this? Any accessors that need documenting? Let's list them in the vignette - the MS will re-cycle the content. If there's anything left to do, let me know if/how I can help. Otherwise let's close this issue

**Comment by EricArcher** [comment]
Whoops - this slipped past my radar. On it today!

**Comment by thibautjombart** [comment]
Awwwesome. =D 
Remember to recompile the vignette, you just need `knit("README.Rmd")`. Just made a few updates, but won't touch it anymore for a bit so should be no conflicts ;)
