### ISSUE TITLE
apex needs phangorn release

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/apex#37]
@KlausVigo CRAN asked me to release a fix for apex, but I realized it now requires the latest (github) version of phangorn. Any chance you can make a release soon?

**Comment by thibautjombart** [comment]
For the record, here is the warning we get testing apex with CRAN version of phangorn:

```
* checking R code for possible problems ... NOTE
multiphyDat2alignment: no visible global function definition for
  ‘phyDat2alignment’
Undefined global functions or variables:
```

We don't get it with the github version.

**Comment by KlausVigo** [comment]
@thibautjombart, I am checking phangorn and dependent packages for submission. If most/all tests are fine I will submit it tomorrow. Wish me luck.  
Do you have set up a nice testing environment, e.g. docker for future submissions??

**Comment by zkamvar** [comment]
FWIW, I wrote up a little entry in poppr's wiki about using docker for testing: https://github.com/grunwaldlab/poppr/wiki/R-CMD-check-with-docker-rocker

Although, the updates are relatively sporadic, but once you have the container set up, it's quite nice.

**Comment by KlausVigo** [comment]
Submitted. Let's pray to the R gods, that it gets accepted ;)

**Comment by thibautjombart** [comment]
May the force be with us.

**Comment by KlausVigo** [comment]
Success!!
