### ISSUE TITLE
apex vignette: move importing data before object classes

### ISSUE THREAD

**Issue by zkamvar** [thibautjombart/apex#44]
After seeing some novice users attempt to import their fasta sequences one by one and then create a multidna object out of them, I realized that this is because it's the first way the user is shown how to import data. If we move the Import Data section before the class definitions, the users would know that  importing with `read.multiFASTA()` is a more optimal choice. What do y'all think?

**Comment by KlausVigo** [comment]
It is a bit like with the R help pages, the interesting bits are at the bottom (in the examples) ;)

**Comment by thibautjombart** [comment]
Yes, that's a good point, a merely a reflection that developers may think about data structure first, while users are more pragmatic.. I agree with you @zkamvar , best to go with what users want to do. Wanna make the change?

**Comment by zkamvar** [comment]
Sure!
