### ISSUE TITLE
CRAN release

### ISSUE THREAD

**Issue by EricArcher** [thibautjombart/apex#46]
I'm ready to submit strataG to CRAN, but winbuilder is throwing errors because of the recent apex accessor changes. If you feel its stable, could the current version of apex be uploaded to CRAN?

**Comment by zkamvar** [comment]
Is there a table listing the current accessor changes? This would be handy to avoid things breaking in this vignette: http://popgen.nescent.org/PopDiffSequenceData.html

**Comment by EricArcher** [comment]
The two main changes were:
- The accessor `setLocusNames` was added to match `getLocusNames` (the vignette seems to use `locusNames`)
- The accessors `getNumSequences`, `getSequenceNames`, and `getSequences` all have the same `exclude.gap.only` argument with the default of `TRUE`.

**Comment by thibautjombart** [comment]
I don't have any objection. Anyone against?

**Comment by EricArcher** [comment]
Not to be pushy, but if it's all good, can we submit?

**Comment by thibautjombart** [comment]
Oh gosh, please push, I had forgotten about it. ':-/

**Comment by thibautjombart** [comment]
Just submitted. Fingers crossed.

**Comment by thibautjombart** [comment]
One CRAN!
