### ISSUE TITLE
Make markdown vignette

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/apex#6]
Doesn't need to be fancy, just to go over the main functionalities. Could be basically what we have in our README.md

**Comment by thibautjombart** [comment]
@KlausVigo @zkamvar @jgx65 Added now. The cool thing is the README.Rmd can now be used to compile README.md, which will include the freshly recompiled vignette. So we now have one doc for the package and the github project.

**Comment by KlausVigo** [comment]
That is really great!!

**Comment by thibautjombart** [comment]
As of 52c06ad1bce84ff671ee9e8caa3e9aa8bfcbcdb5, I get:

``` r
> build_vignettes()
Building apex vignettes
Quitting from lines 162-172 (apex.Rmd) 
Error: processing vignette 'apex.Rmd' failed with diagnostics:
subscript out of bounds
```

@KlausVigo is this the final version or are you still working on it?

**Comment by KlausVigo** [comment]
@thibautjombart  This was the the final version. Can you check the phangorn version, should be 1.99-13 now. build_vignettes() works fine also on my machine, maybe should put the dependency in the DESCRIPTION file. 

```
> build_vignettes()
Building apex vignettes
Hit <Return> to see next plot: 
Hit <Return> to see next plot: 
Moving apex.html, apex.R to inst/doc/
Copying apex.Rmd to inst/doc/
```

NJ still issue needs to be addressed, but setting edge length to 0 should do the trick for now.

**Comment by thibautjombart** [comment]
Will do!

**Comment by thibautjombart** [comment]
I think it is all good now. We could still put a bit more meat around the bone, but that's good enough for a first release.
