### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by KlausVigo** [thibautjombart/apex#7]
I am writing some functions to convert different objects, similar to `multidna2genind`
e.g. `multiphyDat2genind`, `multidna2multiphyDat`, `multiphyDat2multidna`
Should I name these `multidna2multiphyDat(x)`
or use a `as("multiphyDat", x)`
And is it better to rename than the multidna2genind.Rd file to exports.Rd?

**Comment by thibautjombart** [comment]
I would go for xxx2yyy by default, as it is easier and more intuitive.
Otherwise one could define  the method as(....) using setAs, and then make
a wrapper xxx2yyy which calls upon it. But it's pretty much a matter of
taste as far as I'm concerned.
